<?php

/**
 * @file
 * Contains dgc_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dgc_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.dgc_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DGC Custom blocks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_block().
 */
function dgc_blocks_preprocess_block__groupmenus(&$variables) {
  $variables['#cache']['tags'][] = 'node_list';
  $variables['#cache']['contexts'][] = 'group';
}
