apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtwplatform-php
  namespace: {{ .Release.Namespace }}
  labels:
    app: mtwplatform
    role: php
    tier: {{ .Values.tiers.php }}
spec:
  replicas: {{ .Values.replicas.php }}
  nodeSelector:
    tier: {{ .Values.tiers.php }}
  selector:
    matchLabels:
      app: mtwplatform
      role: php
  template:
    metadata:
      labels:
        app: mtwplatform
        role: php
        tier: {{ .Values.tiers.php }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.php.reg }}      
      nodeSelector:
        tier: {{ .Values.tiers.php }}
      containers:
      - name: mtwplatform-php
        image: {{ .Values.images.php.reg }}/{{ .Values.images.php.name }}:{{ .Values.images.php.tag }}
        imagePullPolicy: {{ .Values.images.php.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPorts.php }}
        volumeMounts:
          - name: sf-key
            mountPath: /var/www/webroot/sf
            readOnly: true
        env:
{{ toYaml .Values.env.php | indent 8 }}
        - name: SMTP_USERNAME
          value: {{ .Values.sesUsername }}
        - name: SMTP_PASSWORD
          value: {{ .Values.sesPassword }}
        - name: S3FS_HOSTNAME
          value: {{ .Release.Namespace }}-minio.qak8s.dgchealth.com
        resources:
{{ toYaml .Values.resources.php | indent 10 }}
      volumes:
      - name: sf-key
        secret:
          secretName: mtwplatform-sf-secret
