apiVersion: batch/v1
kind: Job
metadata:
  name: {{ randNumeric 4 | printf "%s-%s" "mtwplatform-site-install" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mtwplatform
    role: job-site-install
    tier: {{ .Values.tiers.php }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      labels:
        app: mtwplatform
        role: job-site-install
        tier: {{ .Values.tiers.php }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.php.reg }}
      nodeSelector:
        tier: {{ .Values.tiers.php }}
      restartPolicy: Never
      containers:
      - name: mtwplatform-php-site-install
        image: {{ .Values.images.php.reg }}/{{ .Values.images.php.name }}:{{ .Values.images.php.tag }}
        imagePullPolicy: {{ .Values.images.php.pullPolicy }}
        command: [ "timeout", "-t", "600", "/usr/local/bin/job-site-install.sh" ]
        workingDir: "/var/www"
        volumeMounts:
          - name: sf-key
            mountPath: /var/www/webroot/sf
            readOnly: true        
        env:
{{ toYaml .Values.env.php | indent 8 }}
        - name: SMTP_USERNAME
          value: {{ .Values.sesUsername }}
        - name: SMTP_PASSWORD
          value: {{ .Values.sesPassword }}
        - name: S3FS_HOSTNAME
          value: {{ .Release.Namespace }}-minio.qak8s.dgchealth.com
      volumes:
      - name: sf-key
        secret:
          secretName: mtwplatform-sf-secret
  backoffLimit: 1
