apiVersion: v1
kind: Service
metadata:
  name: mtwplatform-php
  namespace: {{ .Release.Namespace }}
  labels:
    app: mtwplatform
    role: php
    tier: {{ .Values.tiers.php }}
spec:
  selector:
    app: mtwplatform
    role: php
  ports:
  - port: {{ .Values.containerPorts.php }}
    targetPort: {{ .Values.containerPorts.php }}
    protocol: TCP
