containerPorts:
  php: 9000

tiers:
  php: app

replicas:
  php: 1

images:
  php:
    reg: cireg.dgchealth.com
    name: dgc/mtwplatform-php
    tag: latest
    pullPolicy: Always

resources:
  php:
    requests:
      cpu: "0.25"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "2048Mi"

env:
  php:
  - name: DRUPAL_MYSQL_HOST
    valueFrom:
      secretKeyRef:
        name: mtwplatform-db-secret
        key: endpoint
  - name: MYSQL_USER
    valueFrom:
      secretKeyRef:
        name: mtwplatform-db-secret
        key: username
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mtwplatform-db-secret
        key: password
  - name: MYSQL_DATABASE
    value: "drupal"
  - name: SMTP_ENABLE
    value: "1"
  - name: SMTP_HOST
    value: "smtp.mailtrap.io"
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_PROTOCOL
    value: "tls"
  - name: SMTP_FROM
    value: "mtw-13500b@inbox.mailtrap.io"
  - name: SMTP_FROMNAME
    value: "dgc Health"
  - name: S3FS_DOMAIN
    value: /assets
  - name: S3FS_BUCKETNAME
    value: docker
  - name: S3FS_REGION
    value: us-east-1
  - name: S3FS_ACCESS_KEY
    value: SOME_ACCESS_KEY
  - name: S3FS_SECRET_KEY
    value: SOME_SECRET_KEY
  - name: S3FS_ENABLE
    value: "1"
  - name: S3FS_USE_INSTANCE_PROFILE
    value: "0"
  - name: S3FS_USE_CUSTOM_HOST
    value: "1"
  - name: S3FS_USE_HTTPS
    value: "1"
  - name: S3FS_USE_PATH_STYLE_ENDPOINT
    value: "1"
  - name: S3FS_ROOT
    value: s3fs
  - name: S3FS_SET_PUBLIC_READ_ACL
    value: "1"
  - name: REDIRECT_TO_JAU
    value: "1"

ingress_controller: nginx

sesConfigSetName: test
sesUsername: toBePassedFromJenkinsCredentialsDuringRuntime
sesPassword: toBePassedFromJenkinsCredentialsDuringRuntime
