apiVersion: v1
kind: Service
metadata:
  name: mtwplatform-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: mtwplatform
    role: web
    tier: {{ .Values.tiers.web }}
spec:
  selector:
    app: mtwplatform
    role: web
  ports:
  - port: {{ .Values.containerPorts.web }}
    targetPort: {{ .Values.containerPorts.web }}
    protocol: TCP
