display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Desplazamiento
      fields:
        title:
          label: Title
          separator: ', '
        type:
          label: 'Content type'
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: 'Sin publicar'
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        view_group_content:
          text: View
        edit_group_content:
          text: 'Edit menu link'
        delete_group_content:
          text: 'Delete group content'
        edit_node:
          text: Edit
        delete_node:
          text: Delete
        dropbutton:
          label: Operations
      empty:
        area_text_custom:
          content: 'No content available.'
      arguments:
        gid:
          exception:
            title: All
          title: '{{ arguments.gid|placeholder }} content'
      title: Content
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Content
