display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
      fields:
        id:
          label: ID
          separator: ', '
        drupal_entity__target_id:
          label: Entity
          separator: ', '
        salesforce_id_1:
          separator: ', '
        salesforce_mapping:
          label: Correspondencias
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: 'Enlaces de operación'
  page_1:
    display_title: Page
