label: Media
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
      fields:
        media_bulk_form:
          action_title: Action
        thumbnail__target_id:
          label: Miniatura
          separator: ', '
        name:
          label: 'Nombre del elemento multimedia'
          separator: ', '
        bundle:
          label: Type
          separator: ', '
        uid:
          label: Author
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: 'Sin publicar'
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: Operations
      filters:
        name:
          expose:
            label: 'Nombre del elemento multimedia'
        bundle:
          expose:
            label: Type
        status:
          expose:
            label: 'True'
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: 'Sin publicar'
        langcode:
          expose:
            label: Language
      title: Media
      empty:
        area_text_custom:
          content: 'No hay contenidos multimedia disponibles'
  media_page_list:
    display_title: Media
