display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Desplazamiento
      fields:
        sid:
          separator: ', '
        in_draft:
          separator: ', '
        created:
          label: Created
          separator: ', '
        remote_addr:
          label: 'IP address'
          separator: ', '
        view_webform_submission:
          label: Operations
          text: view
      header:
        result:
          content: 'Mostrando @start - @end de @total'
      arguments:
        in_draft:
          exception:
            title: All
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Action
        sid:
          separator: ', '
        in_draft:
          separator: ', '
        sticky:
          label: Sticky
          separator: ', '
        locked:
          label: Locked
          separator: ', '
        created:
          label: Created
          separator: ', '
        completed:
          separator: ', '
        remote_addr:
          label: 'IP address'
          separator: ', '
        operations:
          label: Operations
      filters:
        sticky:
          expose:
            label: Sticky
        locked:
          expose:
            label: Locked
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Action
        sid:
          separator: ', '
        in_draft:
          separator: ', '
        sticky:
          label: Sticky
          separator: ', '
        locked:
          label: Locked
          separator: ', '
        created:
          label: Created
          separator: ', '
        completed:
          separator: ', '
        remote_addr:
          label: 'IP address'
          separator: ', '
        view_webform_submission:
          label: Operations
          text: view
        edit_webform_submission:
          label: Operations
          text: edit
      filters:
        sticky:
          expose:
            label: Sticky
        locked:
          expose:
            label: Locked
  embed_review:
    display_options:
      fields:
        sid:
          separator: ', '
        in_draft:
          separator: ', '
        sticky:
          label: Sticky
          separator: ', '
        locked:
          label: Locked
          separator: ', '
        created:
          label: Created
          separator: ', '
        completed:
          separator: ', '
        remote_addr:
          label: 'IP address'
          separator: ', '
        view_webform_submission:
          label: Operations
          text: view
      filters:
        sticky:
          expose:
            label: Sticky
        locked:
          expose:
            label: Locked
