label: Files
description: 'Find and manage files.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Desplazamiento
      fields:
        fid:
          label: Fid
        filename:
          label: Name
          separator: ', '
        filemime:
          label: 'MIME type'
        filesize:
          label: Size
        status:
          label: Status
          settings:
            format_custom_false: Temporary
            format_custom_true: Permanent
        created:
          label: 'Upload date'
        changed:
          label: 'Fecha de modificación'
        count:
          label: 'Used in'
      filters:
        filename:
          expose:
            label: Filename
        filemime:
          expose:
            label: 'MIME type'
        status:
          expose:
            label: Status
      title: Files
      empty:
        area_text_custom:
          content: 'No hay archivos disponibles.'
  page_1:
    display_title: 'Vista general de archivos'
    display_options:
      menu:
        title: Files
  page_2:
    display_title: 'Usos del archivo'
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Desplazamiento
      fields:
        entity_label:
          label: Entity
        type:
          label: 'Entity type'
        module:
          label: 'Registrando módulo'
        count:
          label: 'Use count'
      title: 'Usos del archivo'
      arguments:
        fid:
          exception:
            title: All
          title: 'Información de uso del fichero para {{ arguments.fid }}'
