display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
      fields:
        media_bulk_form:
          action_title: Action
      filters:
        status:
          expose:
            label: 'Publishing status'
          group_info:
            label: Published
            group_items:
              1:
                title: Published
        name:
          expose:
            label: Name
      sorts:
        created:
          expose:
            label: 'Newest first'
      title: Media
  page:
    display_title: Page
    display_options:
      menu:
        title: Media
  widget:
    display_title: Widget
    display_options:
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
  widget_table:
    display_options:
      fields:
        name:
          label: Name
        uid:
          label: Author
        changed:
          label: Updated
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
