module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  administerusersbyrole: 0
  allowed_formats: 0
  autologout: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  cer: 0
  ckeditor: 0
  color_field: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  default_content: 0
  devel: 0
  dynamic_entity_reference: 0
  editor: 0
  embed: 0
  encrypt: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  fast404: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  ga_login: 0
  gcontent_field: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  geolocation_google_maps: 0
  gmedia: 0
  gnode: 0
  group: 0
  groupmenu: 0
  groupmenu_block: 0
  hal: 0
  help: 0
  honeypot: 0
  html_formatter: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  key: 0
  kint: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  mail_login: 0
  mailsystem: 0
  maxlength: 0
  media: 0
  media_library: 0
  menu_link: 0
  menu_ui: 0
  message: 0
  message_notify: 0
  metatag: 0
  mimemail: 0
  module_filter: 0
  node: 0
  options: 0
  paragraphs_type_permissions: 0
  password_policy: 0
  password_policy_character_types: 0
  password_policy_characters: 0
  password_policy_length: 0
  path: 0
  pathologic: 0
  real_aes: 0
  redirect: 0
  redirect_after_logout: 0
  salesforce: 0
  salesforce_jwt: 0
  salesforce_logger: 0
  salesforce_mapping: 0
  salesforce_mapping_ui: 0
  salesforce_oauth: 0
  salesforce_push: 0
  salesforce_webform: 0
  serialization: 0
  settings_tray: 0
  smtp: 0
  system: 0
  telephone: 0
  telephone_validation: 0
  text: 0
  tfa: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  typed_data: 0
  user: 0
  dgc_blocks: 0
  dgc_layout: 0
  dgc_media: 0
  dgc_multilingual: 0
  dgc_orgs: 0
  dgc_snippets: 0
  dgc_theme_group: 0
  dgc_users: 0
  dgc_utils: 0
  view_mode_selector: 0
  views_field_formatter: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  xy_grid_layouts: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  dgc: 0
  vseven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
