module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color_field: 0
  config: 0
  config_filter: 0
  config_split: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gcontent_field: 0
  geolocation: 0
  gmedia: 0
  gnode: 0
  group: 0
  groupmenu: 0
  groupmenu_block: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_link: 0
  menu_ui: 0
  module_filter: 0
  node: 0
  options: 0
  paragraphs_type_permissions: 0
  path: 0
  system: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  view_mode_selector: 0
  views_ui: 0
  xy_grid_layouts: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  dgc: 0
  vseven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
