features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
  path: 'public://dgc-logo.png'
favicon:
  use_default: 1
  path: 'public://favicon1.ico'
  mimetype: image/vnd.microsoft.icon
