negotiation:
  language_content:
    method_weights:
      language-session: -20
      language-url: -19
      language-content-entity: -18
      language-user: -17
      language-browser: -16
      language-interface: -15
      language-selected: -14
    enabled:
      language-url: -19
      language-selected: -14
  language_url:
    enabled:
      language-url: 0
      language-url-fallback: 1
  language_interface:
    method_weights:
      language-user-admin: -10
      language-url: -8
      language-session: -6
      language-user: -4
      language-browser: -2
      language-selected: 12
    enabled:
      language-user-admin: -10
      language-url: -8
      language-selected: 12
configurable:
  - language_interface
  - language_content
all:
  - language_interface
  - language_content
  - language_url
