id: mtw_pwd_policy
label: 'MTW Pwd Policy'
password_reset: 90
langcode: en
policy_constraints:
  -
    id: character_types
    character_types: 3
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: special
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: lowercase
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: numeric
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: uppercase
  -
    id: password_length
    character_length: 12
    character_operation: minimum
roles:
  authenticated: authenticated
