features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: themes/custom/dgc/dgc-logo.png
favicon:
  use_default: false
  path: themes/custom/dgc/favicon.ico
  mimetype: image/vnd.microsoft.icon
