favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon1_1.ico'
  url: ''
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: 'public://dgc-logo_1.png'
  url: ''
  use_default: true
_core:
  default_config_hash: KHk8rzK2GMRtdfoAeocFrll8Q7gGtiocl2GF5jnX9cY
