features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://DCATL.jpg'
favicon:
  use_default: false
  path: 'public://DCATL_0.jpg'
  mimetype: image/jpeg
