features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://govcon_4.png'
favicon:
  use_default: false
  path: 'public://govcon_5.png'
  mimetype: image/png
