<?php

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dgc_snippets_theme_suggestions_page(array $variables) {
  $suggestions = [];
  /** @var \Drupal\group\Entity\GroupInterface $group */
  $group = \Drupal::routeMatch()->getParameter('group');
  if (is_numeric($group)) {
    $group = \Drupal::entityTypeManager()->getStorage('group')->load($group);
  }
  /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
  $group_content = \Drupal::routeMatch()->getParameter('group_content');

  if ($group) {
    $sanitized_group_bundle = str_replace('-', '_', $group->bundle());
    $suggestions[] = 'page__group__' . $sanitized_group_bundle;
  }
  if ($group && $group_content) {
    $sanitized_group_content_bundle = str_replace('-', '_', $group_content->bundle());
    $suggestions[] = 'page__group_content';
    $suggestions[] = 'page__group_content__' . $sanitized_group_content_bundle;
  }

  return $suggestions;
}
