text:
  -
    value: "<p>[site:name]&nbsp;Welcome</p>\r\n"
    format: full_html
  -
    value: "<p>[message:field_user:entity:field_fname],</p>\r\n\r\n<p>A site administrator at [site:name] has created an account for you. You may now log in by clicking this link or copying and pasting it into your browser:</p>\r\n\r\n<p>[message:field_login_url]</p>\r\n\r\n<p>This link can only be used once to log in within 24 hours and will lead you to a page where you can set up your password.</p>\r\n\r\n<p>After setting your password, you will be able to log in at [site:login-url] in the future using:</p>\r\n\r\n<p>username: [message:field_user:entity:name] and your password.<br />\r\n&nbsp;</p>\r\n\r\n<p>[message:field_memberships]</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>-- &nbsp;[site:name] team</p>\r\n"
    format: mail
